In [23]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [2]:
x = torch.randn(3, 4)
print(x)

tensor([[-0.3851,  0.7313,  0.0728, -0.4570],
        [-0.5456, -1.7277,  0.8666,  0.6443],
        [ 0.5377, -0.6756, -0.4264,  0.3584]])


In [5]:
y = x.mean(0, keepdim=True)
print(y.shape)
print(y)

torch.Size([1, 4])
tensor([[-0.1310, -0.5573,  0.1710,  0.1819]])


In [8]:
ix = torch.randint(0, x.shape[0], (32,))
ix

tensor([2, 0, 0, 2, 1, 0, 1, 2, 1, 1, 2, 2, 2, 1, 0, 2, 0, 1, 1, 1, 2, 1, 0, 1,
        1, 2, 2, 0, 2, 0, 2, 1])

In [9]:
x[ix]

tensor([[ 0.5377, -0.6756, -0.4264,  0.3584],
        [-0.3851,  0.7313,  0.0728, -0.4570],
        [-0.3851,  0.7313,  0.0728, -0.4570],
        [ 0.5377, -0.6756, -0.4264,  0.3584],
        [-0.5456, -1.7277,  0.8666,  0.6443],
        [-0.3851,  0.7313,  0.0728, -0.4570],
        [-0.5456, -1.7277,  0.8666,  0.6443],
        [ 0.5377, -0.6756, -0.4264,  0.3584],
        [-0.5456, -1.7277,  0.8666,  0.6443],
        [-0.5456, -1.7277,  0.8666,  0.6443],
        [ 0.5377, -0.6756, -0.4264,  0.3584],
        [ 0.5377, -0.6756, -0.4264,  0.3584],
        [ 0.5377, -0.6756, -0.4264,  0.3584],
        [-0.5456, -1.7277,  0.8666,  0.6443],
        [-0.3851,  0.7313,  0.0728, -0.4570],
        [ 0.5377, -0.6756, -0.4264,  0.3584],
        [-0.3851,  0.7313,  0.0728, -0.4570],
        [-0.5456, -1.7277,  0.8666,  0.6443],
        [-0.5456, -1.7277,  0.8666,  0.6443],
        [-0.5456, -1.7277,  0.8666,  0.6443],
        [ 0.5377, -0.6756, -0.4264,  0.3584],
        [-0.5456, -1.7277,  0.8666

In [18]:
a = torch.tensor([[0.98, 0.5, -0.99]])

In [19]:
a

tensor([[ 0.9800,  0.5000, -0.9900]])

In [22]:
(a.abs() > 0.97).float().mean()*100

tensor(66.6667)

In [33]:
a = torch.randn((2,3))
a

tensor([[-0.8676, -1.1155,  0.8177],
        [-0.3646, -0.4404, -0.4901]])

In [43]:
x = a.sum(1, keepdim=True)
x

tensor([[-1.1654],
        [-1.2950]])

In [44]:
x+a

tensor([[-2.0330, -2.2808, -0.3477],
        [-1.6595, -1.7353, -1.7850]])